class AnagramWord {
  final String word;
  final String hint;

  const AnagramWord({required this.word, required this.hint});
}

const easyWords = <AnagramWord>[
  AnagramWord(word: 'HAUS', hint: 'Man wohnt darin'),
  AnagramWord(word: 'BAUM', hint: 'Wächst im Wald'),
  AnagramWord(word: 'HUND', hint: 'Bester Freund des Menschen'),
  AnagramWord(word: 'BUCH', hint: 'Man liest darin'),
  AnagramWord(word: 'BALL', hint: 'Rund und zum Spielen'),
  AnagramWord(word: 'TISCH', hint: 'Möbelstück mit Beinen'),
  AnagramWord(word: 'STUHL', hint: 'Man sitzt darauf'),
  AnagramWord(word: 'STERN', hint: 'Leuchtet am Himmel'),
  AnagramWord(word: 'FISCH', hint: 'Schwimmt im Wasser'),
  AnagramWord(word: 'VOGEL', hint: 'Kann fliegen'),
  AnagramWord(word: 'BLUME', hint: 'Wächst im Garten'),
  AnagramWord(word: 'KATZE', hint: 'Miaut und schnurrt'),
  AnagramWord(word: 'MILCH', hint: 'Weißes Getränk'),
  AnagramWord(word: 'SCHUH', hint: 'Trägt man am Fuß'),
  AnagramWord(word: 'WOLKE', hint: 'Schwebt am Himmel'),
  AnagramWord(word: 'LAMPE', hint: 'Spendet Licht'),
  AnagramWord(word: 'MAUER', hint: 'Aus Steinen gebaut'),
  AnagramWord(word: 'KERZE', hint: 'Brennt mit Flamme'),
  AnagramWord(word: 'GABEL', hint: 'Besteck zum Essen'),
  AnagramWord(word: 'FARBE', hint: 'Rot, Blau oder Grün'),
  AnagramWord(word: 'AUTO', hint: 'Fährt auf der Straße'),
  AnagramWord(word: 'MAUS', hint: 'Kleines Nagetier'),
  AnagramWord(word: 'MOND', hint: 'Leuchtet in der Nacht'),
  AnagramWord(word: 'SONNE', hint: 'Wärmt uns am Tag'),
  AnagramWord(word: 'BROT', hint: 'Isst man zum Frühstück'),
  AnagramWord(word: 'OBST', hint: 'Gesunde Früchte'),
  AnagramWord(word: 'GLAS', hint: 'Daraus trinkt man'),
  AnagramWord(word: 'ZAHN', hint: 'Im Mund zum Kauen'),
  AnagramWord(word: 'HAND', hint: 'Hat fünf Finger'),
  AnagramWord(word: 'KOPF', hint: 'Ganz oben am Körper'),
  AnagramWord(word: 'HUT', hint: 'Trägt man auf dem Kopf'),
  AnagramWord(word: 'RING', hint: 'Schmuck für den Finger'),
  AnagramWord(word: 'UHR', hint: 'Zeigt die Zeit an'),
  AnagramWord(word: 'ZUG', hint: 'Fährt auf Schienen'),
  AnagramWord(word: 'BOOT', hint: 'Schwimmt auf dem See'),
  AnagramWord(word: 'HEMD', hint: 'Kleidungsstück für oben'),
  AnagramWord(word: 'HOSE', hint: 'Kleidungsstück für Beine'),
  AnagramWord(word: 'NASE', hint: 'Mitten im Gesicht'),
  AnagramWord(word: 'OHR', hint: 'Zum Hören da'),
  AnagramWord(word: 'MUND', hint: 'Zum Sprechen und Essen'),
  AnagramWord(word: 'HAAR', hint: 'Wächst auf dem Kopf'),
  AnagramWord(word: 'LAUB', hint: 'Fällt im Herbst'),
  AnagramWord(word: 'LIED', hint: 'Kann man singen'),
  AnagramWord(word: 'FILM', hint: 'Sieht man im Kino'),
  AnagramWord(word: 'GELD', hint: 'Zum Bezahlen'),
  AnagramWord(word: 'GOLD', hint: 'Edles Metall'),
  AnagramWord(word: 'SALZ', hint: 'Würzt das Essen'),
  AnagramWord(word: 'KAFFEE', hint: 'Schwarzes Heißgetränk'),
  AnagramWord(word: 'TEE', hint: 'Heißes Aufgussgetränk'),
  AnagramWord(word: 'SAFT', hint: 'Aus Früchten gepresst'),
  AnagramWord(word: 'EI', hint: 'Legt das Huhn'),
  AnagramWord(word: 'KÄSE', hint: 'Aus Milch gemacht'),
  AnagramWord(word: 'WURST', hint: 'Aufschnitt für Brot'),
  AnagramWord(word: 'OFEN', hint: 'Macht den Raum warm'),
  AnagramWord(word: 'SOFA', hint: 'Zum Entspannen'),
  AnagramWord(word: 'BETT', hint: 'Zum Schlafen'),
  AnagramWord(word: 'BAD', hint: 'Wo man sich wäscht'),
  AnagramWord(word: 'TURM', hint: 'Hohes Bauwerk'),
  AnagramWord(word: 'PARK', hint: 'Grünanlage in der Stadt'),
  AnagramWord(word: 'WALD', hint: 'Viele Bäume zusammen'),
  AnagramWord(word: 'BERG', hint: 'Sehr hohe Erhebung'),
  AnagramWord(word: 'FLUSS', hint: 'Fließendes Gewässer'),
  AnagramWord(word: 'SEE', hint: 'Stehendes Gewässer'),
  AnagramWord(word: 'MEER', hint: 'Großes salziges Wasser'),
  AnagramWord(word: 'SAND', hint: 'Am Strand zu finden'),
  AnagramWord(word: 'STEIN', hint: 'Hart und grau'),
  AnagramWord(word: 'GRAS', hint: 'Grün auf dem Boden'),
  AnagramWord(word: 'BUS', hint: 'Großes Fahrzeug für viele'),
  AnagramWord(word: 'TAXI', hint: 'Auto mit Fahrer mieten'),
];

const mediumWords = <AnagramWord>[
  AnagramWord(word: 'FENSTER', hint: 'Lässt Licht herein'),
  AnagramWord(word: 'GARTEN', hint: 'Grüne Fläche am Haus'),
  AnagramWord(word: 'KUCHEN', hint: 'Süßes Gebäck'),
  AnagramWord(word: 'BRÜCKE', hint: 'Verbindet zwei Ufer'),
  AnagramWord(word: 'SPIEGEL', hint: 'Zeigt dein Spiegelbild'),
  AnagramWord(word: 'HERBST', hint: 'Jahreszeit nach Sommer'),
  AnagramWord(word: 'STRAND', hint: 'Sand am Meer'),
  AnagramWord(word: 'WOLKEN', hint: 'Schweben am Himmel'),
  AnagramWord(word: 'FREUND', hint: 'Wichtige Person im Leben'),
  AnagramWord(word: 'KINDER', hint: 'Junge Menschen'),
  AnagramWord(word: 'FLUGZEUG', hint: 'Fliegt durch die Luft'),
  AnagramWord(word: 'KÜCHE', hint: 'Raum zum Kochen'),
  AnagramWord(word: 'MONTAG', hint: 'Erster Wochentag'),
  AnagramWord(word: 'DONNER', hint: 'Lautes Geräusch bei Gewitter'),
  AnagramWord(word: 'PFLANZE', hint: 'Lebt und wächst'),
  AnagramWord(word: 'MUSTER', hint: 'Sich wiederholendes Design'),
  AnagramWord(word: 'JACKE', hint: 'Kleidung für draußen'),
  AnagramWord(word: 'KISSEN', hint: 'Weich zum Schlafen'),
  AnagramWord(word: 'WASSER', hint: 'Man trinkt es'),
  AnagramWord(word: 'STIMME', hint: 'Kommt beim Sprechen'),
  AnagramWord(word: 'ZEITUNG', hint: 'Zum Lesen von Nachrichten'),
  AnagramWord(word: 'SCHULE', hint: 'Ort zum Lernen'),
  AnagramWord(word: 'LEHRER', hint: 'Unterrichtet Schüler'),
  AnagramWord(word: 'TAFEL', hint: 'Schreibt man mit Kreide drauf'),
  AnagramWord(word: 'KREIDE', hint: 'Zum Schreiben an der Tafel'),
  AnagramWord(word: 'PAPIER', hint: 'Zum Schreiben oder Zeichnen'),
  AnagramWord(word: 'STIFT', hint: 'Damit schreibt man'),
  AnagramWord(word: 'TASCHE', hint: 'Zum Tragen von Sachen'),
  AnagramWord(word: 'BRILLE', hint: 'Hilft beim Sehen'),
  AnagramWord(word: 'HANDY', hint: 'Mobiles Telefon'),
  AnagramWord(word: 'TABLET', hint: 'Flacher Computer'),
  AnagramWord(word: 'KAMERA', hint: 'Macht Fotos'),
  AnagramWord(word: 'MUSIK', hint: 'Zum Anhören und Tanzen'),
  AnagramWord(word: 'GITARRE', hint: 'Instrument mit Saiten'),
  AnagramWord(word: 'KLAVIER', hint: 'Instrument mit Tasten'),
  AnagramWord(word: 'SÄNGER', hint: 'Jemand der singt'),
  AnagramWord(word: 'TANZEN', hint: 'Bewegung zur Musik'),
  AnagramWord(word: 'MALEN', hint: 'Bilder erschaffen'),
  AnagramWord(word: 'KUNST', hint: 'Kreatives Schaffen'),
  AnagramWord(word: 'FARBEN', hint: 'Bunt und vielfältig'),
  AnagramWord(word: 'PINSEL', hint: 'Werkzeug zum Malen'),
  AnagramWord(word: 'BILDER', hint: 'Hängen an der Wand'),
  AnagramWord(word: 'RAHMEN', hint: 'Umrandet ein Bild'),
  AnagramWord(word: 'FOTO', hint: 'Momentaufnahme'),
  AnagramWord(word: 'URLAUB', hint: 'Reise in der Freizeit'),
  AnagramWord(word: 'REISE', hint: 'Unterwegs sein'),
  AnagramWord(word: 'KOFFER', hint: 'Gepäck für die Reise'),
  AnagramWord(word: 'HOTEL', hint: 'Unterkunft im Urlaub'),
  AnagramWord(word: 'ZIMMER', hint: 'Raum in einem Haus'),
  AnagramWord(word: 'BALKON', hint: 'Austritt am Haus'),
  AnagramWord(word: 'KELLER', hint: 'Untergeschoss'),
  AnagramWord(word: 'TREPPE', hint: 'Verbindet Etagen'),
  AnagramWord(word: 'WOHNUNG', hint: 'Darin lebt man'),
  AnagramWord(word: 'STRASSE', hint: 'Weg für Autos'),
  AnagramWord(word: 'AMPEL', hint: 'Regelt den Verkehr'),
  AnagramWord(word: 'SCHILD', hint: 'Gibt Hinweise'),
  AnagramWord(word: 'MARKT', hint: 'Ort zum Einkaufen'),
  AnagramWord(word: 'LADEN', hint: 'Geschäft'),
  AnagramWord(word: 'KASSE', hint: 'Hier bezahlt man'),
  AnagramWord(word: 'PREIS', hint: 'Was es kostet'),
  AnagramWord(word: 'GELD', hint: 'Währung zum Zahlen'),
  AnagramWord(word: 'MÜNZE', hint: 'Hartgeld'),
  AnagramWord(word: 'SCHEIN', hint: 'Papiergeld'),
  AnagramWord(word: 'KONTO', hint: 'Bei der Bank'),
  AnagramWord(word: 'BANK', hint: 'Geldinstitut oder Sitzgelegenheit'),
  AnagramWord(word: 'WINTER', hint: 'Kalte Jahreszeit'),
  AnagramWord(word: 'SCHNEE', hint: 'Fällt im Winter'),
  AnagramWord(word: 'EIS', hint: 'Gefrorenes Wasser'),
  AnagramWord(word: 'SOMMER', hint: 'Warme Jahreszeit'),
  AnagramWord(word: 'FRÜHLING', hint: 'Jahreszeit des Erblühens'),
  AnagramWord(word: 'BLÄTTER', hint: 'Wachsen an Bäumen'),
  AnagramWord(word: 'WURZEL', hint: 'Hält den Baum im Boden'),
  AnagramWord(word: 'GEMÜSE', hint: 'Gesunde Pflanzennahrung'),
  AnagramWord(word: 'SALAT', hint: 'Grüne Blätter zum Essen'),
  AnagramWord(word: 'TOMATE', hint: 'Rote runde Frucht'),
  AnagramWord(word: 'GURKE', hint: 'Langes grünes Gemüse'),
  AnagramWord(word: 'APFEL', hint: 'Rundes Kernobst'),
  AnagramWord(word: 'BIRNE', hint: 'Frucht mit dickerem Ende'),
  AnagramWord(word: 'BANANE', hint: 'Krumme gelbe Frucht'),
  AnagramWord(word: 'TRAUBE', hint: 'Kleine runde Frucht an Rebe'),
  AnagramWord(word: 'ORANGE', hint: 'Zitrusfrucht'),
  AnagramWord(word: 'ZITRONE', hint: 'Sauer macht lustig'),
  AnagramWord(word: 'BÄCKER', hint: 'Backt Brot'),
];

const hardWords = <AnagramWord>[
  AnagramWord(word: 'BIBLIOTHEK', hint: 'Ort mit vielen Büchern'),
  AnagramWord(word: 'SCHMETTERLING', hint: 'Buntes Insekt mit Flügeln'),
  AnagramWord(word: 'ABENTEUER', hint: 'Spannendes Erlebnis'),
  AnagramWord(word: 'GEBURTSTAG', hint: 'Jährliches Fest'),
  AnagramWord(word: 'FRÜHSTÜCK', hint: 'Erste Mahlzeit des Tages'),
  AnagramWord(word: 'HANDSCHUH', hint: 'Wärmt die Hände'),
  AnagramWord(word: 'SCHOKOLADE', hint: 'Süße braune Leckerei'),
  AnagramWord(word: 'WASSERFALL', hint: 'Wasser stürzt in die Tiefe'),
  AnagramWord(word: 'DACHBODEN', hint: 'Raum unter dem Dach'),
  AnagramWord(word: 'ERDBEERE', hint: 'Rote süße Frucht'),
  AnagramWord(word: 'ELEFANT', hint: 'Größtes Landtier'),
  AnagramWord(word: 'UNIVERSUM', hint: 'Alles was existiert'),
  AnagramWord(word: 'GYMNASIUM', hint: 'Weiterführende Schule'),
  AnagramWord(word: 'ZEITSCHRIFT', hint: 'Gedrucktes Magazin'),
  AnagramWord(word: 'KARTOFFEL', hint: 'Knollengemüse'),
  AnagramWord(word: 'SONNENBLUME', hint: 'Große gelbe Blume'),
  AnagramWord(word: 'WÖRTERBUCH', hint: 'Nachschlagewerk für Wörter'),
  AnagramWord(word: 'SPIELPLATZ', hint: 'Ort für Kinder zum Spielen'),
  AnagramWord(word: 'REGENBOGEN', hint: 'Bunter Bogen am Himmel'),
  AnagramWord(word: 'WANDERUNG', hint: 'Langer Spaziergang in der Natur'),
  AnagramWord(word: 'NACHMITTAG', hint: 'Tageszeit nach dem Mittag'),
  AnagramWord(word: 'ABENDESSEN', hint: 'Letzte Mahlzeit des Tages'),
  AnagramWord(word: 'MITTERNACHT', hint: 'Zwölf Uhr nachts'),
  AnagramWord(word: 'WOCHENENDE', hint: 'Samstag und Sonntag'),
  AnagramWord(word: 'FEIERTAG', hint: 'Arbeitsfreier Tag'),
  AnagramWord(word: 'GESCHENK', hint: 'Präsent zum Anlass'),
  AnagramWord(word: 'ÜBERRASCHUNG', hint: 'Unerwartetes Ereignis'),
  AnagramWord(word: 'VERWANDTSCHAFT', hint: 'Familienangehörige'),
  AnagramWord(word: 'GROSSELTERN', hint: 'Oma und Opa'),
  AnagramWord(word: 'GESCHWISTER', hint: 'Bruder und Schwester'),
  AnagramWord(word: 'NACHBARSCHAFT', hint: 'Die Leute nebenan'),
  AnagramWord(word: 'GEMEINSCHAFT', hint: 'Gruppe von Menschen'),
  AnagramWord(word: 'FREUNDSCHAFT', hint: 'Beziehung zwischen Freunden'),
  AnagramWord(word: 'BEKANNTSCHAFT', hint: 'Jemand den man kennt'),
  AnagramWord(word: 'ARBEITSPLATZ', hint: 'Ort wo man arbeitet'),
  AnagramWord(word: 'BÜROGEBÄUDE', hint: 'Haus mit vielen Büros'),
  AnagramWord(word: 'SCHREIBTISCH', hint: 'Tisch zum Arbeiten'),
  AnagramWord(word: 'COMPUTERMAUS', hint: 'Eingabegerät am PC'),
  AnagramWord(word: 'TASTATUR', hint: 'Zum Tippen am PC'),
  AnagramWord(word: 'BILDSCHIRM', hint: 'Zeigt das Bild an'),
  AnagramWord(word: 'DRUCKER', hint: 'Bringt Text auf Papier'),
  AnagramWord(word: 'LADEMEISTER', hint: 'Verantwortlich für Beladung'),
  AnagramWord(word: 'FLUGHAFEN', hint: 'Start und Landung von Flugzeugen'),
  AnagramWord(word: 'BAHNHOF', hint: 'Wo Züge halten'),
  AnagramWord(word: 'HALTESTELLE', hint: 'Wo Busse halten'),
  AnagramWord(word: 'KREUZUNG', hint: 'Wo Straßen sich treffen'),
  AnagramWord(word: 'AUTOBAHN', hint: 'Schnellstraße für Autos'),
  AnagramWord(word: 'FÜHRERSCHEIN', hint: 'Erlaubnis zum Fahren'),
  AnagramWord(word: 'FAHRRADWEG', hint: 'Spur für Radfahrer'),
  AnagramWord(word: 'FUSSGÄNGER', hint: 'Geht zu Fuß'),
  AnagramWord(word: 'BÜRGERSTEIG', hint: 'Weg für Fußgänger'),
  AnagramWord(word: 'SUPERMARKT', hint: 'Großer Lebensmittelladen'),
  AnagramWord(word: 'EINKAUFSWAGEN', hint: 'Wagen für Einkäufe'),
  AnagramWord(word: 'KASSENZETTEL', hint: 'Beleg für den Einkauf'),
  AnagramWord(word: 'RECHNUNG', hint: 'Zahlungsaufforderung'),
  AnagramWord(word: 'PORTEMONNAIE', hint: 'Geldbeutel'),
  AnagramWord(word: 'KREDITKARTE', hint: 'Plastikkarte zum Zahlen'),
  AnagramWord(word: 'SPARSCHWEIN', hint: 'Darin sammelt man Geld'),
  AnagramWord(word: 'WASCHMASCHINE', hint: 'Wäscht die Kleidung'),
  AnagramWord(word: 'SPÜLMASCHINE', hint: 'Wäscht das Geschirr'),
  AnagramWord(word: 'STAUBSAUGER', hint: 'Reinigt den Boden'),
  AnagramWord(word: 'KÜHLSCHRANK', hint: 'Hält Lebensmittel frisch'),
  AnagramWord(word: 'GEFRIERFACH', hint: 'Macht Eis'),
  AnagramWord(word: 'MIKROWELLE', hint: 'Macht Essen schnell warm'),
  AnagramWord(word: 'KAFFEEMASCHINE', hint: 'Brüht Kaffee'),
  AnagramWord(word: 'WASSERKOCHER', hint: 'Erhitzt Wasser'),
  AnagramWord(word: 'HAARTROCKNER', hint: 'Föhnt die Haare'),
  AnagramWord(word: 'ZAHNBÜRSTE', hint: 'Reinigt die Zähne'),
  AnagramWord(word: 'ZAHNPASTA', hint: 'Creme für die Zähne'),
  AnagramWord(word: 'SEIFENBLASE', hint: 'Schwebt und zerplatzt'),
  AnagramWord(word: 'REGENSCHIRM', hint: 'Schützt vor Nässe'),
  AnagramWord(word: 'SONNENSCHEIN', hint: 'Helles Licht vom Stern'),
  AnagramWord(word: 'SCHNEEMANN', hint: 'Figur aus Schnee'),
  AnagramWord(word: 'SCHLITTEN', hint: 'Fährt auf Kufen im Schnee'),
  AnagramWord(word: 'WEIHNACHTEN', hint: 'Fest der Liebe'),
  AnagramWord(word: 'OSTERN', hint: 'Fest mit Eiern'),
  AnagramWord(word: 'SILVESTER', hint: 'Letzter Tag im Jahr'),
  AnagramWord(word: 'NEUJAHR', hint: 'Erster Tag im Jahr'),
  AnagramWord(word: 'FEUERWERK', hint: 'Bunte Lichter am Himmel'),
  AnagramWord(word: 'SONNENUNTERGANG', hint: 'Wenn die Sonne abends sinkt'),
  AnagramWord(word: 'JAHRESZEIT', hint: 'Frühling, Sommer, Herbst oder Winter'),
  AnagramWord(word: 'KLIMAWANDEL', hint: 'Erwärmung unserer Erde'),
  AnagramWord(word: 'VULKANAUSBRUCH', hint: 'Lava fließt aus dem Berg'),
  AnagramWord(word: 'ERDBEBEN', hint: 'Wenn die Erde zittert'),
  AnagramWord(word: 'MONDFINSTERNIS', hint: 'Mond im Schatten der Erde'),
  AnagramWord(word: 'SCHNEEFLOCKE', hint: 'Einzelner Eiskristall aus der Wolke'),
  AnagramWord(word: 'NATURSCHUTZ', hint: 'Schutz der natürlichen Umwelt'),
  AnagramWord(word: 'REGENWALD', hint: 'Tropischer dichter Wald'),
  AnagramWord(word: 'MEERESGRUND', hint: 'Tiefstes des Ozeans'),
  AnagramWord(word: 'JAHRZEHNT', hint: 'Zehn Jahre'),
  AnagramWord(word: 'JAHRHUNDERT', hint: 'Hundert Jahre'),
  AnagramWord(word: 'GEWITTERWOLKE', hint: 'Bringt Blitz und Donner'),
  AnagramWord(word: 'SONNENSYSTEM', hint: 'Unsere Planeten um die Sonne'),
  AnagramWord(word: 'WASSERKREISLAUF', hint: 'Verdunstung und Niederschlag'),
  AnagramWord(word: 'ERDATMOSPHÄRE', hint: 'Lufthülle um unseren Planeten'),
  AnagramWord(word: 'SCHIMPANSE', hint: 'Menschenähnlicher Affe'),
  AnagramWord(word: 'NILPFERD', hint: 'Dickes Tier am Wasser'),
  AnagramWord(word: 'SCHILDKRÖTE', hint: 'Reptil mit hartem Panzer'),
  AnagramWord(word: 'EICHHÖRNCHEN', hint: 'Klettert auf Bäumen und knabbert Nüsse'),
  AnagramWord(word: 'TAUSENDFÜSSLER', hint: 'Krabbelt mit sehr vielen Beinen'),
  AnagramWord(word: 'FLEDERMAUS', hint: 'Fliegt nachts und schläft kopfüber'),
  AnagramWord(word: 'GÜRTELTIER', hint: 'Trägt eine schützende Rüstung'),
  AnagramWord(word: 'SALAMANDER', hint: 'Amphibie mit buntem Muster'),
  AnagramWord(word: 'SEEPFERDCHEN', hint: 'Kleines Tier im Meer, steht aufrecht'),
  AnagramWord(word: 'GLÜHWÜRMCHEN', hint: 'Leuchtet in der Sommernacht'),
  AnagramWord(word: 'NASHORN', hint: 'Großes Tier mit Horn auf der Nase'),
  AnagramWord(word: 'KROKODIL', hint: 'Reptil mit riesigem Maul'),
  AnagramWord(word: 'GEPARD', hint: 'Schnellstes Landtier der Welt'),
  AnagramWord(word: 'FLAMINGO', hint: 'Rosa Vogel steht auf einem Bein'),
  AnagramWord(word: 'DELFIN', hint: 'Intelligentes Meeressäugetier'),
  AnagramWord(word: 'KOALABÄR', hint: 'Frisst Eukalyptus in Australien'),
  AnagramWord(word: 'KÄNGURU', hint: 'Springt mit Beutel in Australien'),
  AnagramWord(word: 'HOCHSPRUNG', hint: 'Über eine Latte springen'),
  AnagramWord(word: 'WEITSPRUNG', hint: 'So weit wie möglich springen'),
  AnagramWord(word: 'STAFFELLAUF', hint: 'Laufen mit Stab-Übergabe'),
  AnagramWord(word: 'SCHWIMMBAD', hint: 'Ort zum Schwimmen'),
  AnagramWord(word: 'TENNISPLATZ', hint: 'Feld für Tennis'),
  AnagramWord(word: 'KLETTERPARK', hint: 'Park mit Kletterseilen und Bäumen'),
  AnagramWord(word: 'SKIFAHREN', hint: 'Wintersport auf Brettern'),
  AnagramWord(word: 'RADFAHREN', hint: 'Sport auf zwei Rädern'),
  AnagramWord(word: 'BODENTURNEN', hint: 'Turnen auf der Matte ohne Geräte'),
  AnagramWord(word: 'HÜRDENLAUF', hint: 'Sprinten über Hindernisse'),
  AnagramWord(word: 'HAMMERWERFEN', hint: 'Leichtathletik mit schwerem Gerät'),
  AnagramWord(word: 'STABHOCHSPRUNG', hint: 'Über die Latte mit einem Stab'),
  AnagramWord(word: 'HALBMARATHON', hint: 'Lauf über 21 Kilometer'),
  AnagramWord(word: 'KRANKENHAUS', hint: 'Ort für Kranke und Verletzte'),
  AnagramWord(word: 'FEUERWEHR', hint: 'Löscht Brände und rettet Menschen'),
  AnagramWord(word: 'UNIVERSITÄT', hint: 'Höchste Bildungsstätte'),
  AnagramWord(word: 'KINDERGARTEN', hint: 'Bildungseinrichtung vor der Schule'),
  AnagramWord(word: 'BERUFSSCHULE', hint: 'Lernen für den Beruf'),
  AnagramWord(word: 'OPERNHAUS', hint: 'Wo Oper aufgeführt wird'),
  AnagramWord(word: 'KUNSTMUSEUM', hint: 'Zeigt Gemälde und Skulpturen'),
  AnagramWord(word: 'JUGENDHERBERGE', hint: 'Günstige Unterkunft für Reisende'),
  AnagramWord(word: 'POLIZEIWACHE', hint: 'Sitz der Polizei'),
  AnagramWord(word: 'STANDESAMT', hint: 'Wo man offiziell heiratet'),
  AnagramWord(word: 'FINANZAMT', hint: 'Behörde für Steuern'),
  AnagramWord(word: 'STADTBIBLIOTHEK', hint: 'Stadtbücherei zum Ausleihen'),
  AnagramWord(word: 'WOHNZIMMER', hint: 'Hauptraum im Haus'),
  AnagramWord(word: 'SCHLAFZIMMER', hint: 'Raum zum Schlafen'),
  AnagramWord(word: 'KINDERZIMMER', hint: 'Raum der Kinder im Haus'),
  AnagramWord(word: 'BADEZIMMER', hint: 'Raum mit Dusche und Badewanne'),
  AnagramWord(word: 'ESSZIMMER', hint: 'Raum zum gemeinsamen Essen'),
  AnagramWord(word: 'ARBEITSZIMMER', hint: 'Raum mit Schreibtisch'),
  AnagramWord(word: 'GÄSTEZIMMER', hint: 'Raum für Besucher'),
  AnagramWord(word: 'GARTENHAUS', hint: 'Kleines Haus im Garten'),
  AnagramWord(word: 'WISSENSCHAFT', hint: 'Systematisches Erkunden der Welt'),
  AnagramWord(word: 'EXPERIMENT', hint: 'Versuch im Labor'),
  AnagramWord(word: 'MIKROSKOP', hint: 'Macht winzig Kleines sichtbar'),
  AnagramWord(word: 'TELESKOP', hint: 'Sieht weit in den Weltraum'),
  AnagramWord(word: 'THERMOMETER', hint: 'Misst die Temperatur'),
  AnagramWord(word: 'GLÜHBIRNE', hint: 'Elektrische Lichtquelle'),
  AnagramWord(word: 'KERNKRAFTWERK', hint: 'Strom aus Kernenergie'),
  AnagramWord(word: 'WINDTURBINE', hint: 'Erzeugt Strom aus Wind'),
  AnagramWord(word: 'STECKDOSE', hint: 'Anschluss für elektrische Geräte'),
  AnagramWord(word: 'FERNBEDIENUNG', hint: 'Steuert den Fernseher aus der Ferne'),
  AnagramWord(word: 'SATELLITENSCHÜSSEL', hint: 'Empfängt Signale aus dem All'),
  AnagramWord(word: 'KOPFHÖRER', hint: 'Musik direkt am Ohr'),
  AnagramWord(word: 'LADEKABEL', hint: 'Gibt dem Akku Strom'),
  AnagramWord(word: 'FESTPLATTE', hint: 'Speichert Daten im Computer'),
  AnagramWord(word: 'BETRIEBSSYSTEM', hint: 'Software die den Computer steuert'),
  AnagramWord(word: 'APFELSTRUDEL', hint: 'Süßes Gebäck mit Apfelfüllung'),
  AnagramWord(word: 'LEBKUCHEN', hint: 'Würziges Weihnachtsgebäck'),
  AnagramWord(word: 'SCHWARZWÄLDER', hint: 'Berühmte Torte mit Kirschen'),
  AnagramWord(word: 'RINDFLEISCH', hint: 'Fleisch vom Rind'),
  AnagramWord(word: 'BLUMENKOHL', hint: 'Weißes Gemüse in Röschen'),
  AnagramWord(word: 'ROSENKOHL', hint: 'Kleiner Kohl aus Brüssel'),
  AnagramWord(word: 'KNOBLAUCH', hint: 'Würzige Knolle gegen Vampire'),
  AnagramWord(word: 'ZUCCHINI', hint: 'Grünes Sommergemüse'),
  AnagramWord(word: 'BROKKOLI', hint: 'Grünes Gemüse in kleinen Bäumchen'),
  AnagramWord(word: 'PFEFFERKUCHEN', hint: 'Würziges Gebäck mit Gewürzen'),
  AnagramWord(word: 'BIENENSTICH', hint: 'Kuchen mit Mandeln und Sahne'),
  AnagramWord(word: 'NUSSKIPFERL', hint: 'Kleines Gebäck mit Nüssen'),
  AnagramWord(word: 'SAUERTEIG', hint: 'Triebmittel für Brot'),
  AnagramWord(word: 'VOLLKORNBROT', hint: 'Brot aus ganzem Korn'),
  AnagramWord(word: 'KOPFSCHMERZEN', hint: 'Schmerzen im Kopf'),
  AnagramWord(word: 'RÜCKENSCHMERZEN', hint: 'Schmerzen im Rücken'),
  AnagramWord(word: 'ERKÄLTUNG', hint: 'Schnupfen und Husten im Winter'),
  AnagramWord(word: 'MEDIKAMENT', hint: 'Mittel gegen Krankheit'),
  AnagramWord(word: 'NOTAUFNAHME', hint: 'Notfall-Bereich im Krankenhaus'),
  AnagramWord(word: 'BLUTDRUCK', hint: 'Druck des Blutes in den Adern'),
  AnagramWord(word: 'KRANKENWAGEN', hint: 'Eilt schnell zu Verletzten'),
  AnagramWord(word: 'RÖNTGENAUFNAHME', hint: 'Bild durch den Körper'),
  AnagramWord(word: 'ELEKTRIKER', hint: 'Arbeitet mit Strom'),
  AnagramWord(word: 'MECHANIKER', hint: 'Repariert Maschinen'),
  AnagramWord(word: 'SCHREINER', hint: 'Baut Möbel aus Holz'),
  AnagramWord(word: 'ZIMMERMANN', hint: 'Baut mit Holz'),
  AnagramWord(word: 'FEUERWEHRMANN', hint: 'Löscht Brände'),
  AnagramWord(word: 'KINDERARZT', hint: 'Arzt für Kinder'),
  AnagramWord(word: 'TIERARZT', hint: 'Arzt für Tiere'),
  AnagramWord(word: 'BÄCKERMEISTER', hint: 'Meister des Brotbackens'),
  AnagramWord(word: 'RECHTSANWALT', hint: 'Berät in juristischen Fragen'),
  AnagramWord(word: 'ARCHITEKT', hint: 'Entwirft Gebäude'),
  AnagramWord(word: 'MUSIKER', hint: 'Spielt Instrumente'),
  AnagramWord(word: 'SCHAUSPIELER', hint: 'Spielt Rollen auf der Bühne'),
  AnagramWord(word: 'FOTOGRAF', hint: 'Macht Bilder mit der Kamera'),
  AnagramWord(word: 'VERANTWORTUNG', hint: 'Pflicht für etwas einzustehen'),
  AnagramWord(word: 'ENTSCHEIDUNG', hint: 'Wählen zwischen Möglichkeiten'),
  AnagramWord(word: 'GERECHTIGKEIT', hint: 'Fairness und Gleichheit'),
  AnagramWord(word: 'ENTSCHULDIGUNG', hint: 'Wenn man um Verzeihung bittet'),
  AnagramWord(word: 'ÜBERZEUGUNG', hint: 'Feste innere Meinung'),
  AnagramWord(word: 'BEGEISTERUNG', hint: 'Große Freude und Enthusiasmus'),
  AnagramWord(word: 'VERSTÄNDNIS', hint: 'Einfühlen in eine Situation'),
  AnagramWord(word: 'ENTWICKLUNG', hint: 'Wachstum und Veränderung'),
  AnagramWord(word: 'ERINNERUNG', hint: 'Gedanke an etwas Vergangenes'),
  AnagramWord(word: 'AUSZEICHNUNG', hint: 'Ehrung für besondere Leistung'),
  AnagramWord(word: 'VORSTELLUNG', hint: 'Ein Bild im Kopf oder eine Darbietung'),
  AnagramWord(word: 'BEOBACHTUNG', hint: 'Aufmerksames Anschauen'),
  AnagramWord(word: 'ÜBERLEGUNG', hint: 'Nachdenken über etwas'),
  AnagramWord(word: 'VERBINDUNG', hint: 'Zusammenschluss zweier Dinge'),
  AnagramWord(word: 'ERMUTIGUNG', hint: 'Jemanden anspornen und stärken'),
  AnagramWord(word: 'BESCHEIDENHEIT', hint: 'Nicht prahlen mit sich selbst'),
  AnagramWord(word: 'SELBSTVERTRAUEN', hint: 'Glaube an die eigenen Fähigkeiten'),
];
